<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
# импортируем основные библиотеки
import pandas as pd
import numpy as np

from sklearn.metrics import r2_score

In [2]:
# загружаем датасет
db = pd.read_csv('/datasets/insurance.csv')

In [3]:
# проверяем на корректность  загрузки
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
db.head(5)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

**Вывод:** В дадасете 5000 строк. Пропуски отсутствуют.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Нет, рузультат при умножении признаков исходной матрицы на обратную не изменится.

**Обоснование:** 
Как и было выше написано, формула линейной регрессии вычесляется так:

$$a = Xw + w0$$

Для более схожей формулы с теорией добавил w0 - величина сдвига весов.

Если признаки умножить на любую обратимую квадратную матрицу (Не важно какие именно значения будут в самой матрице, главное что бы она была обратимой) и точно так же умножим веса но уже на обратную матрицу, то получим следующую формулу: 

$$a = XA^{-1}Aw + w0$$

Квадратная матрица необходима именно для того, что бы можно было вернуться к исходной матрице X


**Обоснование:**

Используемые свойства:
$$
(AB)^T=B^T A^T
$$
$$
(AB)^{-1} = B^{-1} A^{-1}
$$
$$
A A^{-1} = A^{-1} A = E
$$
$$
AE = EA = A
$$
Доказательство:
$$
a = Xw = XEw = XPP^{-1}w = (XP)P^{-1}w = (XP)w'
$$
\
Требуется доказать, что предсказания не изменятся, имеем  $a =  Xw$,   $a' = X'w'$
\
\
$$
    w = (X^T X)^{-1} X^T y
$$
\
$$
w' = ((XP)^T XP)^{-1} (XP)^T y
$$
$$
w' = (P^T (X^T X) P)^{-1} (XP)^T y
$$
$$
w' = (P^T (X^T X) P)^{-1} P^T X^T y
$$



Расскроем скобки 
$$w' = (P^{T})^{-1}(X^{T}X)^{-1}P^{-1}P^{T}X^{T}y $$

По условию данное разложение будет равнятся еденичной матрце, поэтому можно сократить выражение
$(P^{T})^{-1}P^{T} = E$


В результате у нас получается 
$$ w' = (X^{T}X)^{-1}P^{-1}X^{T}y$$

Расскрываем скобки далее
$$ w' = (X^{T})^{-1}X^{-1}P^{-1}X^{T}y $$

По свойсту $(X^{T})^{-1}X^{-1} = X$ сократим выражение дальше

$$ w' = XP^{-1}X^{T}y $$


Т.к   $XX^{T} = P$ то итоговые веса равны

$$ w' = PP^{-1} $$


Подставляем значение в формулу и получаем 

$$ a = (XP)w' = (XP)PP^{-1} = X(PP)P^{-1} = XP^{-1} $$


$$ w' = (AB)^{-1}X^{T}y = B^{-1}A^{-1}X^{T}y $$

Далее расскроем ранее сокращенные выражения 

$$ w' = P^{-1}(X^{T}X)^{-1}X^{T}y $$

Выражение $(X^{T}X)^{-1}X^{T}y$ является матрицей весов регресии a, т.е. $w$. Тогда получается что 

$$ w' = P^{-1}w $$
$$ a' = (XP)w' = XPP^{-1}w = Xw = a $$

In [5]:
# наглядный эксперемент 
a = np.array([[1,2,3],
             [8,4,5],
             [4,3,2]])

print(a @ np.linalg.inv(a))
print()
print(np.linalg.inv(a) @ a)

[[ 1.00000000e+00  2.77555756e-17 -3.33066907e-16]
 [-2.22044605e-16  1.00000000e+00 -1.11022302e-16]
 [-2.22044605e-16 -5.55111512e-17  1.00000000e+00]]

[[ 1.00000000e+00  0.00000000e+00 -8.32667268e-17]
 [ 0.00000000e+00  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00]]


Из примера видим, что  $A^{-1}A$  или $AA^{-1}$ при любом варинте умножения выдают по своей диагонали еденичную матрицу. Именно за счёт этого удастся получать одинаковый результат при умножении на исходную матрицу и веса векторов. Так же при умножении матрицы на еденичную матрицу результат не меняется.


## Алгоритм преобразования

**Алгоритм**


- Создадим любую квадратную матрицу, основываясь на размерности нашей исходной тестовой выборки. К примеру, числа в квадратной матрицу пусть будут от -100 до 100.
- найдем произведение обратной матрицы на квадратную 
- умножим получившиюся матрицу на матрицу значений датасета


In [6]:
# поделим датасет на фичи и таргет
features  = db.drop('Страховые выплаты', axis = 1)
target = db['Страховые выплаты']

In [7]:
# квадратная матрица
sq_matrix_r = np.random.normal(-100, 100, (features.shape[1], features.shape[1]))

In [8]:
sq_matrix_inv = np.linalg.inv(sq_matrix_r)

In [9]:
Defent_matrix =  features @ sq_matrix_inv

In [10]:
print(Defent_matrix)

                0           1            2            3
0     1438.188112 -495.889975  1389.198724 -1517.314521
1     1102.771455 -380.253577  1065.474192 -1163.605041
2      609.672882 -210.232373   589.122944  -643.344225
3     1208.216556 -416.567312  1166.803643 -1274.543127
4      757.219857 -261.104486   731.548937  -798.950860
...           ...         ...          ...          ...
4995  1035.012149 -356.863313   999.718551 -1091.940880
4996  1518.772234 -523.656973  1466.866460 -1602.230518
4997   982.398110 -338.712662   948.776505 -1036.360444
4998   947.771722 -326.779075   915.377239  -999.861431
4999  1176.862805 -405.776839  1136.671266 -1241.550320

[5000 rows x 4 columns]


## Проверка алгоритма

Создам класс для написания линейной регресии.

In [11]:

class LinearRegression:
    
    """Линейная регрессия"""
    
    def fit(self, train_features, train_target):
        
        """Получение весов """
        
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = (np.linalg.inv(X.T.dot(X))).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        
        """вычисление результата"""
        
        return test_features.dot(self.w) + self.w0
    

In [12]:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
result_1 = r2_score(target, predictions)

In [13]:
model = LinearRegression()
model.fit(Defent_matrix, target)
predictions = model.predict(Defent_matrix)
result_2 = r2_score(target, predictions)

In [14]:
print(result_1, result_2)
print('результаты равны? ', result_1 - result_2)

0.42494550286668 0.4249455028536483
результаты равны?  1.3031686840747625e-11


**Вывод:** При преобразовании матриц результат предсказания изменяется несущественно. 